### ISSUE TITLE
Python 3,unichr not defined in util.py error

### ISSUE THREAD

**Issue by shivareddyiirs** [XLSForm/pyxform#161]
![image](https://user-images.githubusercontent.com/5653512/32818555-f4e87eac-c9e9-11e7-8932-f10ad387c6ec.png)
in util.py line no 18 , unichr is not defined error is coming when I am using pyxform in my plugin in QGIS 3 (i.e python 3 environment)

**Comment by ukanga** [comment]
See https://github.com/XLSForm/pyxform/pull/164#issuecomment-354723090

I will suggest you test this on the python terminal in isolation and see if the similar error occurs.
```python
>>> from pyxform.utils import unichr
>>> unichr(10000)
```

**Comment by shivareddyiirs** [comment]
below in my response when i tried first line in my python console in qgis3:

```
from pyxform.utils import unichr
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\shiva\AppData\Roaming\Python\Python36\site-packages\pyxform\__init__.py", line 8, in <module>
    from pyxform.survey import Survey  # noqa
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\shiva\AppData\Roaming\Python\Python36\site-packages\pyxform\survey.py", line 11, in <module>
    from pyxform.instance import SurveyInstance
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\shiva\AppData\Roaming\Python\Python36\site-packages\pyxform\instance.py", line 1, in <module>
    from pyxform.xform_instance_parser import parse_xform_instance
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\shiva\AppData\Roaming\Python\Python36\site-packages\pyxform\xform_instance_parser.py", line 8, in <module>
    from pyxform.utils import unicode
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\shiva\AppData\Roaming\Python\Python36\site-packages\pyxform\utils.py", line 18, in <module>
    unichr = unichr
NameError: name 'unichr' is not defined
```
