### ISSUE TITLE
pyxform installation problem inside python

### ISSUE THREAD

**Issue by shivareddyiirs** [XLSForm/pyxform#181]
When  I am trying to install pyxform inside my python code using  below lines:
```
import pip
pip.main(['install','--user','--no-cache-dir'])
```
Following is the error:

Collecting pyxform
  Downloading pyxform-0.10.0-py2.py3-none-any.whl (1.6MB)
Exception:
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\download.py", line 585, in _download_url
    progress_indicator = DownloadProgressBar(max=total_length).iter
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\utils\ui.py", line 158, in __init__
    super(WindowsMixin, self).__init__(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\utils\ui.py", line 82, in __init__
    super(InterruptibleMixin, self).__init__(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\utils\ui.py", line 118, in __init__
    super(DownloadProgressMixin, self).__init__(*args, **kwargs)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\pip\_vendor\progress\helpers.py", line 58, in __init__
    if self.file.isatty() and self.hide_cursor:
AttributeError: 'writeOut' object has no attribute 'isatty'
2

**Comment by lognaturel** [comment]
@shivareddyiirs apologies for the silence here. This appears to be an issue with your Python configuration, not one with pyxform. Are you trying to run pyxform from within QGIS? I would try with a standalone Python installation.

**Comment by shivareddyiirs** [comment]
Yes I was trying to run pyxform within QGIS
