### ISSUE TITLE
Logging handler causes breakage interacting with other packages

### ISSUE THREAD

**Issue by axonxorz** [XLSForm/pyxform#401]
I'm using pyxform as part of an asynchronous task with Celery. Celery performs some deep magic on the standard Python logging system when forking, and chokes since 07301f95

Celery attempts to start it's workers a few times before failing

```Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/home/user/opt/virtualenvs/project/lib/python2.7/site-packages/billiard/process.py", line 315, in _bootstrap
    handler.createLock()
TypeError: unbound method createLock() must be called with NullHandler instance as first argument (got nothing instead)
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/home/user/opt/virtualenvs/project/lib/python2.7/site-packages/billiard/process.py", line 315, in _bootstrap
    handler.createLock()
TypeError: unbound method createLock() must be called with NullHandler instance as first argument (got nothing instead)
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/home/user/opt/virtualenvs/project/lib/python2.7/site-packages/billiard/process.py", line 315, in _bootstrap
    handler.createLock()
TypeError: unbound method createLock() must be called with NullHandler instance as first argument (got nothing instead)
Process ForkPoolWorker-5:
Traceback (most recent call last):
  File "/home/user/opt/virtualenvs/project/lib/python2.7/site-packages/billiard/process.py", line 315, in _bootstrap
    handler.createLock()
TypeError: unbound method createLock() must be called with NullHandler instance as first argument (got nothing instead)
Process Beat:
Traceback (most recent call last):
  File "/home/user/opt/virtualenvs/project/lib/python2.7/site-packages/billiard/process.py", line 315, in _bootstrap
    handler.createLock()
TypeError: unbound method createLock() must be called with NullHandler instance as first argument (got nothing instead)
```

**Comment by lindsay-stevens** [comment]
Fixed by #402
