### ISSUE TITLE
Invalid expression causes an exception

### ISSUE THREAD

**Issue by spatialdude** [XLSForm/pyxform#72]
An invalid expression, such as `$(new_post_installNo)='2'` (incorrect parentheses) causes an exception such as -

```
Traceback (most recent call last):
  File "/Users/elvin/py/pyxform/xls2xform.py", line 94, in <module>
    main_cli()
  File "/Users/elvin/py/pyxform/xls2xform.py", line 81, in main_cli
    response['message'] = str(e)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u034e' in position 209: ordinal not in range(128)
```

**Comment by spatialdude** [comment]
The problem was the ODKValidateError exception handling.

Solution was a simple fix to the exception handler -

```python
response['message'] = e.args[0].encode('utf-8')
```
