### ISSUE TITLE
Validation error with external instances

### ISSUE THREAD

**Issue by sjudeng** [XLSForm/pyxform#87]
Hi,

I'm getting a validation error in `xls2xform` when using `select_one_from_file` in my XLSForm. If I skip validation it loads through ODK Aggregate and works with Enketo.

XLSForm content is attached (see [select_from_file_test.xlsx](https://github.com/XLSForm/pyxform/files/488142/select_from_file_test.xlsx)) and shown below.

survey:

| type | name | label | choice_filter |
| --- | --- | --- | --- |
| select_one_from_file states.csv | State | Select State |  |

choices:

| list_name | name | label |
| --- | --- | --- |
| states | name | label |

settings:

| form_title | form_id |
| --- | --- |
| select_from_file test | select_from_file_test |

The validation error is shown below.

```
python xls2xform.py select_from_file_test.xlsx select_from_file_test.xml
Traceback (most recent call last):
  File "xls2xform.py", line 94, in <module>
    main_cli()
  File "xls2xform.py", line 86, in main_cli
    args.path_to_XLSForm, args.output_path, args.skip_validate)
  File "xls2xform.py", line 23, in xls2xform_convert
    survey.print_xform_to_file(xform_path, validate=validate, warnings=warnings)
  File "/src/pyxform/pyxform/survey.py", line 507, in print_xform_to_file
    warnings.extend(check_xform(path))
  File "/src/pyxform/pyxform/odk_validate/__init__.py", line 133, in check_xform
    'ODK Validate Errors:\n' + _cleanup_errors(stderr))
odk_validate.ODKValidateError: ODK Validate Errors:
Selection choice label text and image uri are both missing for: ${State} choice: 1.

Selection value is missing for: ${State} choice: 1. The XML is invalid.

>> Xform is invalid! See above for errors and warnings.

Result: Invalid
```

Below is the XML generated if I run with `--skip_validate`. This loads without error in ODK Aggregate and the form works as expected in Enketo. So should the validation pass?

``` xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>select from file test</h:title>
    <model>
      <instance>
        <select_from_file_test id="select_from_file_test">
          <State/>
          <meta>
            <instanceID/>
          </meta>
        </select_from_file_test>
      </instance>
      <instance id="states" src="jr://file-csv/states.csv">
        <root>
          <item>
            <name/>
            <label/>
          </item>
        </root>
      </instance>
      <bind nodeset="/select_from_file_test/State" type="select1"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/select_from_file_test/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <select1 ref="/select_from_file_test/State">
      <label>Select State</label>
      <itemset nodeset="instance('states')/root/item">
        <value ref="name"/>
        <label ref="label"/>
      </itemset>
    </select1>
  </h:body>
</h:html>
```

**Comment by MartijnR** [comment]
Yes, I can reproduce this. Seems that we have to fool ODK Validate further by adding dummy values for `<name>` (and perhaps `<label>`) in the dummy content for the external instance.
